# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json


PackageIdentifier: Icecat.Icecat
PackageVersion: "115.12.0esr"
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://icecatbrowser.org/assets/icecat/115.12.0/icecat-115.12.0.multilang.win64.installer.exe
  InstallerSha256: 364a5f93d00835f9a7e7fa5865115c35841d7f3e0a7dd14b5c4594d2f96e1271
ManifestType: installer
ManifestVersion: 1.6.0



