# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json


PackageIdentifier: Icecat.Icecat
PackageVersion: "115.8.0esr"
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://icecatbrowser.org/assets/icecat/115.8.0/icecat-115.8.0.win64.installer.exe
  InstallerSha256: e1fbcfd81ae532f4316743ea6e850e90aede0ba808c503b77dd7dee0f520b27c
ManifestType: installer
ManifestVersion: 1.4.0


