# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Icecat.Icecat
PackageVersion: 115.3.1esr
InstallerType: exe
InstallModes: 
 - "silent"
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
- InstallerUrl: https://codeberg.org/chippy/icecat-for-windows/releases/download/115.3.1esr/icecat-115.3.1.en-it-nl-de-fr.win64.Silent.installer.EXE
  Architecture: x64
  InstallerSha256: 20630B6764676EDF1DD6A6519D3F27385B2C52605A61AAD92E1C9A7B0C818D53
ManifestType: installer
ManifestVersion: 1.5.0

