# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json


PackageIdentifier: Icecat.Icecat
PackageVersion: "115.9.1esr"
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://icecatbrowser.org/assets/icecat/115.9.1/icecat-115.9.1.en-US.win64.installer.exe
  InstallerSha256: 75982f803c8ad7ec365eb76964fdf8da252996c5ba8f69f2df52628ae4ad1cd9
ManifestType: installer
ManifestVersion: 1.6.0



